DROP TABLE IF EXISTS t_event;
CREATE TABLE t_order_outbox (
    EVENT_ID            UUID PRIMARY KEY UNIQUE,
    AGGREGATE_ID        VARCHAR(75) NOT NULL,
    VERSION             INTEGER NOT NULL,
    EVENT_TYPE          VARCHAR(75) NOT NULL,
    PAYLOAD             TEXT NOT NULL
);


